version: "3.8"

services:
  db:
    image: postgres:16
    container_name: encomiendas_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: clave123
      POSTGRES_DB: encomiendas_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql

volumes:
  pgdata: